# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &config_project_defaults
  working_directory: ~/repo

executors:
  node_default:
    docker:
      - image: circleci/node:12.13.0

orbs:
  aws-cli: circleci/aws-cli@0.1.22

commands:
  configure_aws:
    description: "Sets up AWS profiles, CLI and configuration"
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          profile-name: highsugar

jobs:
  deploy_ibm_cf:
    <<: *config_project_defaults
    executor: node_default
    steps:
      - checkout
      - run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
      - run: which ibmcloud
      - run: ibmcloud login -u $CF_USERNAME -p $CF_PASSWORD -r us-south
      - run: ibmcloud target -o $CF_USERNAME -s prod -r us-south
#      - run: |
#          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
#          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
#          sudo apt-get update
#          sudo apt-get install cf-cli
#      - run: which cf && cf --version
#      - run: cf login -a "api.us-south.cf.cloud.ibm.com" -u $CF_USERNAME -p $CF_PASSWORD -o $CF_USERNAME -s prod
#      - run: cf push
      - run:
          working_directory: ~/repo/ibmcloudfoundryapp
          command: npm run deploy
  deploy_wp_single:
    <<: *config_project_defaults
    executor: node_default
    steps:
      - checkout
      - configure_aws
      - run:
          working_directory: ~/repo/awswordpress/single-instance
          command: >-
            aws cloudformation deploy
            --template-file template.yaml
            --stack-name cs5224-wp-single
            --parameter-overrides DBName=wordpressdb DBPassword=$DB_PASS DBRootPassword=$DB_PASS DBUser=$DB_USER InstanceType=t2.nano KeyName=nusinstanceskeypair SSHLocation=0.0.0.0/0
            --profile highsugar
            --region $AWS_REGION
  deploy_wp_multiaz:
    <<: *config_project_defaults
    executor: node_default
    steps:
      - checkout
      - configure_aws
      - run: echo TODO

workflows:
  version: 2
  master_flow:
    jobs:
      - deploy_ibm_cf:
          filters:
            branches:
              only:
                - master
      - deploy_wp_single:
          filters:
            branches:
              only:
                - master
      - deploy_wp_multiaz:
          filters:
            branches:
              only:
                - master
